### ISSUE TITLE
can you support zip volume?

### ISSUE THREAD

**Issue by dreamcanfly** [geromueller/zstream-cpp#1]
if i have some zip volumes, can i use your lib to get the stream of them?

**Comment by geromueller** [comment]
Hi,

the short answer is no. But, you can read the compressed parts of a ZIP file with this lib. It would easily be possible to write little code to read the ZIP data structures and point the stream to the right position: https://en.wikipedia.org/wiki/Zip_(file_format)
I have little time at the moment, so a PR is highly welcome!

**Comment by geromueller** [comment]
For a full blown solution check: https://github.com/gdraheim/zziplib

**Comment by dreamcanfly** [comment]
I'm sorry I don't know how to solve this problem, and I want to use it in windows, can you give me some tips?

**Comment by dreamcanfly** [comment]
您的信件已经收到，将尽快给您答复！                                     ——汪野
