### ISSUE TITLE
When compression level 0 is used, end of file is still compressed

### ISSUE THREAD

**Issue by mdelambilly** [geromueller/zstream-cpp#3]
with this source code :
int main(void) {
	ofstream os("test.txt.gz");
	ogzstream gz(os, 0);
	for (size_t i = 0; i < 2000; i++) {
		gz << drand48() << endl;
	}
	cout << gz.get_zerr() << endl;
	return 0;
}

end of file looks like :
0.458663
0.590483
0.180235
i▒▒kF

**Comment by geromueller** [comment]
Hi, sorry for the late reply! This is intended, since the file needs to be a valid gzip file.
